{{- if .Values.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "opencart.fullname" . }}-opencart
  labels:
    app.kubernetes.io/name: {{ include "opencart.name" . }}
    helm.sh/chart: {{ include "opencart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.opencart.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.opencart.size | quote }}
{{- if .Values.persistence.opencart.storageClass }}
{{- if (eq "-" .Values.persistence.opencart.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.opencart.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}
