apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opencart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "opencart.name" . }}
    helm.sh/chart: {{ include "opencart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.opencartPassword }}
  opencart-password: {{ default "" .Values.opencartPassword | b64enc | quote }}
  {{ else }}
  opencart-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  smtp-password: {{ default "" .Values.smtpPassword | b64enc | quote }}
